### ISSUE TITLE
need to create .composeinfo file

### ISSUE THREAD

**Issue by ausil** [release-engineering/productmd#37]
beaker only supports importing .composeinfo files for composes. They are not going to port to using productmd as they plan to use pdc as the datastore. we need to make .composeinfo files to ensure that composes are importable into beaker

**Comment by dmach** [comment]
I'm sorry but I'm rejecting this request for following reasons:
* it's a hack - I'd rather improve beaker than maintain a compatibility format for 1 use case
* if beaker will import data from pdc, then I recommend to wait for this feature
 * my opinion is that this wasn't a good decision, because by reading composes only from PDC limits beaker from working with 3rd party composes, "unofficial" test composes, etc.

**Comment by lubomir** [comment]
I have written a script that can generate the file and sent a pull request to compose-utils:
https://pagure.io/compose-utils/pull-request/17
